[project]
name = "fingering-suggestor"
version = "0.1.0"
description = "Suggests piano fingerings for MusicXML sheet music"
readme = "README.md"
authors = [
    { name = "Travis Xiong", email = "travisxiong19@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "music21>=10.5.0",
]

[project.scripts]
fingering-suggestor = "fingering_suggestor:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
